# Server configs
server:
  server_to_ping: 8.8.8.8
  web_server_port: 8000
  # The maximum latency you expect to experience or as the ISP states
  # In milliseconds
  max_latency: 700
  # How long to wait before considering the ping to have failed
  # In milliseconds
  pinger_timeout: 500 

# People to notify
emails:
  - user@domain
  - user@domain
  - user@domain
