# Server configs
server:
  server_to_ping: 8.8.8.8
  web_server_port: 8000
  # The maximum latency you expect to experience or as the ISP states
  # In milliseconds
  max_latency: 500

# People to notify
emails:
  - user@domain.com
  - user@domain.com
  - user@domain.com
